Repository aws-ia/taskcat, pull requests merged in 2018-10, with the labels that each got.

#144 Switch to yaml.safe_load calls
  .bumpversion.cfg
  .travis.yml
  requirements.txt
  setup.py
  taskcat/stacker.py
  taskcat/utils.py
Labels: security patch

#81 Adding ability to accept source-key-prefix to allow replacement of th…
  bin/alchemist
  taskcat/deployer.py
Labels: enhancement

#157 Forcing lowercase bucket names. Fixes #155
  taskcat/stacker.py
Labels: bug

#156 Tidy up Docker installers
  README.md
  installer/docker-install-develop
  installer/docker-install-master
  installer/docker-installer.sh
Labels: enhancement
