Repository aws-ia/taskcat, pull requests merged in 2018-11, with the labels that each got.

#166 Updates to bucket mismatch wording; adding override validations
  README.md
  examples/sample-taskcat-project/ci/debug-input.json
  examples/sample-taskcat-project/ci/taskcat.yml
  examples/sample-taskcat-project/ci/taskcat_project_override.json
  examples/sample-taskcat-project/templates/debug-yaml.template
  examples/sample-taskcat-project/templates/debug.template
  taskcat/stacker.py
Labels: enhancement

#175 enable an optional list of files to NOT delete
  taskcat/s3_sync.py
Labels: enhancement

#163 automatically generate lambda packages
  README.md
  bin/taskcat
  taskcat/__init__.py
  taskcat/common_utils.py
  taskcat/lambda_build.py
  taskcat/stacker.py
Labels: enhancement

#187 Release taskcat [0.8.6]
  .bumpversion.cfg
  README.md
  setup.py
Labels: documentation, enhancement

#197 Fixes deep cleanup
  taskcat/stacker.py
Labels: bug
